<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="shreejits-mbp.cambridge.ibm.com" name="Default test" tests="6" failures="3" timestamp="8 Nov 2017 17:24:28 GMT" time="5.069" errors="0">
  <testcase name="feature" time="2.623" classname="com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.runner.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: Actual response Time MILLISECONDS: 683 Expected response time MILLISECONDS: 600">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: Actual response Time MILLISECONDS: 683 Expected response time MILLISECONDS: 600
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.runner.TestRunner.feature(TestRunner.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Actual response Time MILLISECONDS: 683 Expected response time MILLISECONDS: 600
	at org.testng.Assert.fail(Assert.java:94)
	at com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.domain.RESTFactory.verifyResponseTime(RESTFactory.java:223)
	at com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.stepdefinitions.StepDefinitionsRestServices.response_time_is_within_s(StepDefinitionsRestServices.java:125)
	at ✽.And response time is within 600 ms(Feature01_CreateNewUser.feature:21)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="0.642" classname="com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.runner.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [Shreejit] but found [null]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [Shreejit] but found [null]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.runner.TestRunner.feature(TestRunner.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [Shreejit] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:130)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.domain.RESTFactory.verifyResponseData(RESTFactory.java:132)
	at com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.stepdefinitions.StepDefinitionsRestServices.response_contains(StepDefinitionsRestServices.java:100)
	at ✽.And response body contains(Feature02_RetrieveUser.feature:14)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="0.484" classname="com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.runner.TestRunner"/>
  <testcase name="feature" time="0.262" classname="com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.runner.TestRunner"/>
  <testcase name="feature" time="0.251" classname="com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.runner.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: Actual response type: application/json Expected response type: text">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: Actual response type: application/json Expected response type: text
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.runner.TestRunner.feature(TestRunner.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Actual response type: application/json Expected response type: text
	at org.testng.Assert.fail(Assert.java:94)
	at com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.domain.RESTFactory.verifyResponseType(RESTFactory.java:94)
	at com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.stepdefinitions.StepDefinitionsRestServices.response_type_should_be(StepDefinitionsRestServices.java:91)
	at ✽.And response type should be "text"(Feature05_Login.feature:12)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="0.201" classname="com.ibmwatsonhealth.devopsservices.swaggertestasset.swaggerParserUtility.runner.TestRunner"/>
</testsuite> <!-- Default test -->
